import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { delight, lato, roboto } from "./fonts";
import { PrivyProvider } from "./context/PrivyContext";
import { SolanaProvider } from "./context/SolanaContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${roboto.variable} ${delight.variable} antialiased`}
      >
        <PrivyProvider>
          <SolanaProvider network="devnet">{children}</SolanaProvider>
        </PrivyProvider>
      </body>
    </html>
  );
}
